INSERT INTO countries (id, name) VALUES ('AB','Abkhazia');
INSERT INTO countries (id, name) VALUES ('AU','Australia');
INSERT INTO countries (id, name) VALUES ('AT','Austria');
INSERT INTO countries (id, name) VALUES ('AZ','Azerbaijan');
INSERT INTO countries (id, name) VALUES ('AL','Albania');
INSERT INTO countries (id, name) VALUES ('DZ','Algeria');
INSERT INTO countries (id, name) VALUES ('AS','American Samoa');
INSERT INTO countries (id, name) VALUES ('AI','Anguilla');
INSERT INTO countries (id, name) VALUES ('AO','Angola');
INSERT INTO countries (id, name) VALUES ('AD','Andorra');
INSERT INTO countries (id, name) VALUES ('AQ','Antarctica');
INSERT INTO countries (id, name) VALUES ('AG','Antigua and Barbuda');
INSERT INTO countries (id, name) VALUES ('AR','Argentina');
INSERT INTO countries (id, name) VALUES ('AM','Armenia');
INSERT INTO countries (id, name) VALUES ('AW','Aruba');
INSERT INTO countries (id, name) VALUES ('AF','Afghanistan');
INSERT INTO countries (id, name) VALUES ('BS','Bahamas');
INSERT INTO countries (id, name) VALUES ('BD','Bangladesh');
INSERT INTO countries (id, name) VALUES ('BB','Barbados');
INSERT INTO countries (id, name) VALUES ('BH','Bahrain');
INSERT INTO countries (id, name) VALUES ('BY','Belarus');
INSERT INTO countries (id, name) VALUES ('BZ','Belize');
INSERT INTO countries (id, name) VALUES ('BE','Belgium');
INSERT INTO countries (id, name) VALUES ('BJ','Benin');
INSERT INTO countries (id, name) VALUES ('BM','Bermuda');
INSERT INTO countries (id, name) VALUES ('BG','Bulgaria');
INSERT INTO countries (id, name) VALUES ('BO','Bolivia, plurinational state of');
INSERT INTO countries (id, name) VALUES ('BQ','Bonaire, Sint Eustatius and Saba');
INSERT INTO countries (id, name) VALUES ('BA','Bosnia and Herzegovina');
INSERT INTO countries (id, name) VALUES ('BW','Botswana');
INSERT INTO countries (id, name) VALUES ('BR','Brazil');
INSERT INTO countries (id, name) VALUES ('IO','British Indian Ocean Territory');
INSERT INTO countries (id, name) VALUES ('BN','Brunei Darussalam');
INSERT INTO countries (id, name) VALUES ('BF','Burkina Faso');
INSERT INTO countries (id, name) VALUES ('BI','Burundi');
INSERT INTO countries (id, name) VALUES ('BT','Bhutan');
INSERT INTO countries (id, name) VALUES ('VU','Vanuatu');
INSERT INTO countries (id, name) VALUES ('HU','Hungary');
INSERT INTO countries (id, name) VALUES ('VE','Venezuela');
INSERT INTO countries (id, name) VALUES ('VG','Virgin Islands, British');
INSERT INTO countries (id, name) VALUES ('VI','Virgin Islands, U.S.');
INSERT INTO countries (id, name) VALUES ('VN','Vietnam');
INSERT INTO countries (id, name) VALUES ('GA','Gabon');
INSERT INTO countries (id, name) VALUES ('HT','Haiti');
INSERT INTO countries (id, name) VALUES ('GY','Guyana');
INSERT INTO countries (id, name) VALUES ('GM','Gambia');
INSERT INTO countries (id, name) VALUES ('GH','Ghana');
INSERT INTO countries (id, name) VALUES ('GP','Guadeloupe');
INSERT INTO countries (id, name) VALUES ('GT','Guatemala');
INSERT INTO countries (id, name) VALUES ('GN','Guinea');
INSERT INTO countries (id, name) VALUES ('GW','Guinea-Bissau');
INSERT INTO countries (id, name) VALUES ('DE','Germany');
INSERT INTO countries (id, name) VALUES ('GG','Guernsey');
INSERT INTO countries (id, name) VALUES ('GI','Gibraltar');
INSERT INTO countries (id, name) VALUES ('HN','Honduras');
INSERT INTO countries (id, name) VALUES ('HK','Hong Kong');
INSERT INTO countries (id, name) VALUES ('GD','Grenada');
INSERT INTO countries (id, name) VALUES ('GL','Greenland');
INSERT INTO countries (id, name) VALUES ('GR','Greece');
INSERT INTO countries (id, name) VALUES ('GE','Georgia');
INSERT INTO countries (id, name) VALUES ('GU','Guam');
INSERT INTO countries (id, name) VALUES ('DK','Denmark');
INSERT INTO countries (id, name) VALUES ('JE','Jersey');
INSERT INTO countries (id, name) VALUES ('DJ','Djibouti');
INSERT INTO countries (id, name) VALUES ('DM','Dominica');
INSERT INTO countries (id, name) VALUES ('DO','Dominican Republic');
INSERT INTO countries (id, name) VALUES ('EG','Egypt');
INSERT INTO countries (id, name) VALUES ('ZM','Zambia');
INSERT INTO countries (id, name) VALUES ('EH','Western Sahara');
INSERT INTO countries (id, name) VALUES ('ZW','Zimbabwe');
INSERT INTO countries (id, name) VALUES ('IL','Israel');
INSERT INTO countries (id, name) VALUES ('IN','India');
INSERT INTO countries (id, name) VALUES ('ID','Indonesia');
INSERT INTO countries (id, name) VALUES ('JO','Jordan');
INSERT INTO countries (id, name) VALUES ('IQ','Iraq');
INSERT INTO countries (id, name) VALUES ('IR','Iran, Islamic Republic of');
INSERT INTO countries (id, name) VALUES ('IE','Ireland');
INSERT INTO countries (id, name) VALUES ('IS','Iceland');
INSERT INTO countries (id, name) VALUES ('ES','Spain');
INSERT INTO countries (id, name) VALUES ('IT','Italy');
INSERT INTO countries (id, name) VALUES ('YE','Yemen');
INSERT INTO countries (id, name) VALUES ('CV','Cape Verde');
INSERT INTO countries (id, name) VALUES ('KZ','Kazakhstan');
INSERT INTO countries (id, name) VALUES ('KH','Cambodia');
INSERT INTO countries (id, name) VALUES ('CM','Cameroon');
INSERT INTO countries (id, name) VALUES ('CA','Canada');
INSERT INTO countries (id, name) VALUES ('QA','Qatar');
INSERT INTO countries (id, name) VALUES ('KE','Kenya');
INSERT INTO countries (id, name) VALUES ('CY','Cyprus');
INSERT INTO countries (id, name) VALUES ('KG','Kyrgyzstan');
INSERT INTO countries (id, name) VALUES ('KI','Kiribati');
INSERT INTO countries (id, name) VALUES ('CN','China');
INSERT INTO countries (id, name) VALUES ('CC','Cocos (Keeling) Islands');
INSERT INTO countries (id, name) VALUES ('CO','Colombia');
INSERT INTO countries (id, name) VALUES ('KM','Comoros');
INSERT INTO countries (id, name) VALUES ('CG','Congo');
INSERT INTO countries (id, name) VALUES ('CD','Congo, Democratic Republic of the');
INSERT INTO countries (id, name) VALUES ('KP','Korea, Democratic People''s republic of');
INSERT INTO countries (id, name) VALUES ('KR','Korea, Republic of');
INSERT INTO countries (id, name) VALUES ('CR','Costa Rica');
INSERT INTO countries (id, name) VALUES ('CI','Cote d''Ivoire');
INSERT INTO countries (id, name) VALUES ('CU','Cuba');
INSERT INTO countries (id, name) VALUES ('KW','Kuwait');
INSERT INTO countries (id, name) VALUES ('CW','Curaçao');
INSERT INTO countries (id, name) VALUES ('LA','Lao People''s Democratic Republic');
INSERT INTO countries (id, name) VALUES ('LV','Latvia');
INSERT INTO countries (id, name) VALUES ('LS','Lesotho');
INSERT INTO countries (id, name) VALUES ('LB','Lebanon');
INSERT INTO countries (id, name) VALUES ('LY','Libyan Arab Jamahiriya');
INSERT INTO countries (id, name) VALUES ('LR','Liberia');
INSERT INTO countries (id, name) VALUES ('LI','Liechtenstein');
INSERT INTO countries (id, name) VALUES ('LT','Lithuania');
INSERT INTO countries (id, name) VALUES ('LU','Luxembourg');
INSERT INTO countries (id, name) VALUES ('MU','Mauritius');
INSERT INTO countries (id, name) VALUES ('MR','Mauritania');
INSERT INTO countries (id, name) VALUES ('MG','Madagascar');
INSERT INTO countries (id, name) VALUES ('YT','Mayotte');
INSERT INTO countries (id, name) VALUES ('MO','Macao');
INSERT INTO countries (id, name) VALUES ('MW','Malawi');
INSERT INTO countries (id, name) VALUES ('MY','Malaysia');
INSERT INTO countries (id, name) VALUES ('ML','Mali');
INSERT INTO countries (id, name) VALUES ('UM','United States Minor Outlying Islands');
INSERT INTO countries (id, name) VALUES ('MV','Maldives');
INSERT INTO countries (id, name) VALUES ('MT','Malta');
INSERT INTO countries (id, name) VALUES ('MA','Morocco');
INSERT INTO countries (id, name) VALUES ('MQ','Martinique');
INSERT INTO countries (id, name) VALUES ('MH','Marshall Islands');
INSERT INTO countries (id, name) VALUES ('MX','Mexico');
INSERT INTO countries (id, name) VALUES ('FM','Micronesia, Federated States of');
INSERT INTO countries (id, name) VALUES ('MZ','Mozambique');
INSERT INTO countries (id, name) VALUES ('MD','Moldova');
INSERT INTO countries (id, name) VALUES ('MC','Monaco');
INSERT INTO countries (id, name) VALUES ('MN','Mongolia');
INSERT INTO countries (id, name) VALUES ('MS','Montserrat');
INSERT INTO countries (id, name) VALUES ('MM','Burma');
INSERT INTO countries (id, name) VALUES ('NA','Namibia');
INSERT INTO countries (id, name) VALUES ('NR','Nauru');
INSERT INTO countries (id, name) VALUES ('NP','Nepal');
INSERT INTO countries (id, name) VALUES ('NE','Niger');
INSERT INTO countries (id, name) VALUES ('NG','Nigeria');
INSERT INTO countries (id, name) VALUES ('NL','Netherlands');
INSERT INTO countries (id, name) VALUES ('NI','Nicaragua');
INSERT INTO countries (id, name) VALUES ('NU','Niue');
INSERT INTO countries (id, name) VALUES ('NZ','New Zealand');
INSERT INTO countries (id, name) VALUES ('NC','New Caledonia');
INSERT INTO countries (id, name) VALUES ('NO','Norway');
INSERT INTO countries (id, name) VALUES ('AE','United Arab Emirates');
INSERT INTO countries (id, name) VALUES ('OM','Oman');
INSERT INTO countries (id, name) VALUES ('BV','Bouvet Island');
INSERT INTO countries (id, name) VALUES ('IM','Isle of Man');
INSERT INTO countries (id, name) VALUES ('NF','Norfolk Island');
INSERT INTO countries (id, name) VALUES ('CX','Christmas Island');
INSERT INTO countries (id, name) VALUES ('HM','Heard Island and McDonald Islands');
INSERT INTO countries (id, name) VALUES ('KY','Cayman Islands');
INSERT INTO countries (id, name) VALUES ('CK','Cook Islands');
INSERT INTO countries (id, name) VALUES ('TC','Turks and Caicos Islands');
INSERT INTO countries (id, name) VALUES ('PK','Pakistan');
INSERT INTO countries (id, name) VALUES ('PW','Palau');
INSERT INTO countries (id, name) VALUES ('PS','Palestinian Territory, Occupied');
INSERT INTO countries (id, name) VALUES ('PA','Panama');
INSERT INTO countries (id, name) VALUES ('VA','Holy See (Vatican City State)');
INSERT INTO countries (id, name) VALUES ('PG','Papua New Guinea');
INSERT INTO countries (id, name) VALUES ('PY','Paraguay');
INSERT INTO countries (id, name) VALUES ('PE','Peru');
INSERT INTO countries (id, name) VALUES ('PN','Pitcairn');
INSERT INTO countries (id, name) VALUES ('PL','Poland');
INSERT INTO countries (id, name) VALUES ('PT','Portugal');
INSERT INTO countries (id, name) VALUES ('PR','Puerto Rico');
INSERT INTO countries (id, name) VALUES ('MK','Macedonia, The Former Yugoslav Republic Of');
INSERT INTO countries (id, name) VALUES ('RE','Reunion');
INSERT INTO countries (id, name) VALUES ('RU','Russian Federation');
INSERT INTO countries (id, name) VALUES ('RW','Rwanda');
INSERT INTO countries (id, name) VALUES ('RO','Romania');
INSERT INTO countries (id, name) VALUES ('WS','Samoa');
INSERT INTO countries (id, name) VALUES ('SM','San Marino');
INSERT INTO countries (id, name) VALUES ('ST','Sao Tome and Principe');
INSERT INTO countries (id, name) VALUES ('SA','Saudi Arabia');
INSERT INTO countries (id, name) VALUES ('SH','Saint Helena, Ascension And Tristan Da Cunha');
INSERT INTO countries (id, name) VALUES ('MP','Northern Mariana Islands');
INSERT INTO countries (id, name) VALUES ('BL','Saint Barthélemy');
INSERT INTO countries (id, name) VALUES ('MF','Saint Martin (French Part)');
INSERT INTO countries (id, name) VALUES ('SN','Senegal');
INSERT INTO countries (id, name) VALUES ('VC','Saint Vincent and the Grenadines');
INSERT INTO countries (id, name) VALUES ('KN','Saint Kitts and Nevis');
INSERT INTO countries (id, name) VALUES ('LC','Saint Lucia');
INSERT INTO countries (id, name) VALUES ('PM','Saint Pierre and Miquelon');
INSERT INTO countries (id, name) VALUES ('RS','Serbia');
INSERT INTO countries (id, name) VALUES ('SC','Seychelles');
INSERT INTO countries (id, name) VALUES ('SG','Singapore');
INSERT INTO countries (id, name) VALUES ('SX','Sint Maarten');
INSERT INTO countries (id, name) VALUES ('SY','Syrian Arab Republic');
INSERT INTO countries (id, name) VALUES ('SK','Slovakia');
INSERT INTO countries (id, name) VALUES ('SI','Slovenia');
INSERT INTO countries (id, name) VALUES ('GB','United Kingdom');
INSERT INTO countries (id, name) VALUES ('US','United States');
INSERT INTO countries (id, name) VALUES ('SB','Solomon Islands');
INSERT INTO countries (id, name) VALUES ('SO','Somalia');
INSERT INTO countries (id, name) VALUES ('SD','Sudan');
INSERT INTO countries (id, name) VALUES ('SR','Suriname');
INSERT INTO countries (id, name) VALUES ('SL','Sierra Leone');
INSERT INTO countries (id, name) VALUES ('TJ','Tajikistan');
INSERT INTO countries (id, name) VALUES ('TH','Thailand');
INSERT INTO countries (id, name) VALUES ('TW','Taiwan, Province of China');
INSERT INTO countries (id, name) VALUES ('TZ','Tanzania, United Republic Of');
INSERT INTO countries (id, name) VALUES ('TL','Timor-Leste');
INSERT INTO countries (id, name) VALUES ('TG','Togo');
INSERT INTO countries (id, name) VALUES ('TK','Tokelau');
INSERT INTO countries (id, name) VALUES ('TO','Tonga');
INSERT INTO countries (id, name) VALUES ('TT','Trinidad and Tobago');
INSERT INTO countries (id, name) VALUES ('TV','Tuvalu');
INSERT INTO countries (id, name) VALUES ('TN','Tunisia');
INSERT INTO countries (id, name) VALUES ('TM','Turkmenistan');
INSERT INTO countries (id, name) VALUES ('TR','Turkey');
INSERT INTO countries (id, name) VALUES ('UG','Uganda');
INSERT INTO countries (id, name) VALUES ('UZ','Uzbekistan');
INSERT INTO countries (id, name) VALUES ('UA','Ukraine');
INSERT INTO countries (id, name) VALUES ('WF','Wallis and Futuna');
INSERT INTO countries (id, name) VALUES ('UY','Uruguay');
INSERT INTO countries (id, name) VALUES ('FO','Faroe Islands');
INSERT INTO countries (id, name) VALUES ('FJ','Fiji');
INSERT INTO countries (id, name) VALUES ('PH','Philippines');
INSERT INTO countries (id, name) VALUES ('FI','Finland');
INSERT INTO countries (id, name) VALUES ('FK','Falkland Islands (Malvinas)');
INSERT INTO countries (id, name) VALUES ('FR','France');
INSERT INTO countries (id, name) VALUES ('GF','French Guiana');
INSERT INTO countries (id, name) VALUES ('PF','French Polynesia');
INSERT INTO countries (id, name) VALUES ('TF','French Southern Territories');
INSERT INTO countries (id, name) VALUES ('HR','Croatia');
INSERT INTO countries (id, name) VALUES ('CF','Central African Republic');
INSERT INTO countries (id, name) VALUES ('TD','Chad');
INSERT INTO countries (id, name) VALUES ('ME','Montenegro');
INSERT INTO countries (id, name) VALUES ('CZ','Czech Republic');
INSERT INTO countries (id, name) VALUES ('CL','Chile');
INSERT INTO countries (id, name) VALUES ('CH','Switzerland');
INSERT INTO countries (id, name) VALUES ('SE','Sweden');
INSERT INTO countries (id, name) VALUES ('SJ','Svalbard and Jan Mayen');
INSERT INTO countries (id, name) VALUES ('LK','Sri Lanka');
INSERT INTO countries (id, name) VALUES ('EC','Ecuador');
INSERT INTO countries (id, name) VALUES ('GQ','Equatorial Guinea');
INSERT INTO countries (id, name) VALUES ('AX','Åland Islands');
INSERT INTO countries (id, name) VALUES ('SV','El Salvador');
INSERT INTO countries (id, name) VALUES ('ER','Eritrea');
INSERT INTO countries (id, name) VALUES ('SZ','Eswatini');
INSERT INTO countries (id, name) VALUES ('EE','Estonia');
INSERT INTO countries (id, name) VALUES ('ET','Ethiopia');
INSERT INTO countries (id, name) VALUES ('ZA','South Africa');
INSERT INTO countries (id, name) VALUES ('GS','South Georgia and the South Sandwich Islands');
INSERT INTO countries (id, name) VALUES ('OS','South Ossetia');
INSERT INTO countries (id, name) VALUES ('SS','South Sudan');
INSERT INTO countries (id, name) VALUES ('JM','Jamaica');
INSERT INTO countries (id, name) VALUES ('JP','Japan');


INSERT INTO currencies(id, code, name) VALUES ('AED','784','UAE Dirham');
INSERT INTO currencies(id, code, name) VALUES ('AFN','971','Afghani');
INSERT INTO currencies(id, code, name) VALUES ('ALL','008','Lek');
INSERT INTO currencies(id, code, name) VALUES ('AMD','051','Armenian Dram');
INSERT INTO currencies(id, code, name) VALUES ('ANG','532','Netherlands Antillean Guilder');
INSERT INTO currencies(id, code, name) VALUES ('AOA','973','Kwanza');
INSERT INTO currencies(id, code, name) VALUES ('ARS','032','Argentine Peso');
INSERT INTO currencies(id, code, name) VALUES ('AUD','036','Australian Dollar');
INSERT INTO currencies(id, code, name) VALUES ('AWG','533','Aruban Florin');
INSERT INTO currencies(id, code, name) VALUES ('AZN','944','Azerbaijanian Manat');
INSERT INTO currencies(id, code, name) VALUES ('BAM','977','Convertible Mark');
INSERT INTO currencies(id, code, name) VALUES ('BBD','052','Barbados Dollar');
INSERT INTO currencies(id, code, name) VALUES ('BDT','050','Taka');
INSERT INTO currencies(id, code, name) VALUES ('BGN','975','Bulgarian Lev');
INSERT INTO currencies(id, code, name) VALUES ('BHD','048','Bahraini Dinar');
INSERT INTO currencies(id, code, name) VALUES ('BIF','108','Burundi Franc');
INSERT INTO currencies(id, code, name) VALUES ('BMD','060','Bermudian Dollar');
INSERT INTO currencies(id, code, name) VALUES ('BND','096','Brunei Dollar');
INSERT INTO currencies(id, code, name) VALUES ('BOB','068','Boliviano');
INSERT INTO currencies(id, code, name) VALUES ('BOV','984','Mvdol');
INSERT INTO currencies(id, code, name) VALUES ('BRL','986','Brazilian Real');
INSERT INTO currencies(id, code, name) VALUES ('BSD','044','Bahamian Dollar');
INSERT INTO currencies(id, code, name) VALUES ('BTN','064','Ngultrum');
INSERT INTO currencies(id, code, name) VALUES ('BWP','072','Pula');
INSERT INTO currencies(id, code, name) VALUES ('BYN','933','Belarussian Ruble');
INSERT INTO currencies(id, code, name) VALUES ('BZD','084','Belize Dollar');
INSERT INTO currencies(id, code, name) VALUES ('CAD','124','Canadian Dollar');
INSERT INTO currencies(id, code, name) VALUES ('CDF','976','Congolese Franc');
INSERT INTO currencies(id, code, name) VALUES ('CHE','947','WIR Euro');
INSERT INTO currencies(id, code, name) VALUES ('CHF','756','Swiss Franc');
INSERT INTO currencies(id, code, name) VALUES ('CHW','948','WIR Franc');
INSERT INTO currencies(id, code, name) VALUES ('CLF','990','Unidad de Fomento');
INSERT INTO currencies(id, code, name) VALUES ('CLP','152','Chilean Peso');
INSERT INTO currencies(id, code, name) VALUES ('CNY','156','Yuan Renminbi');
INSERT INTO currencies(id, code, name) VALUES ('COP','170','Colombian Peso');
INSERT INTO currencies(id, code, name) VALUES ('COU','970','Unidad de Valor Real');
INSERT INTO currencies(id, code, name) VALUES ('CRC','188','Costa Rican Colon');
INSERT INTO currencies(id, code, name) VALUES ('CUC','931','Peso Convertible');
INSERT INTO currencies(id, code, name) VALUES ('CUP','192','Cuban Peso');
INSERT INTO currencies(id, code, name) VALUES ('CVE','132','Cabo Verde Escudo');
INSERT INTO currencies(id, code, name) VALUES ('CZK','203','Czech Koruna');
INSERT INTO currencies(id, code, name) VALUES ('DJF','262','Djibouti Franc');
INSERT INTO currencies(id, code, name) VALUES ('DKK','208','Danish Krone');
INSERT INTO currencies(id, code, name) VALUES ('DOP','214','Dominican Peso');
INSERT INTO currencies(id, code, name) VALUES ('DZD','012','Algerian Dinar');
INSERT INTO currencies(id, code, name) VALUES ('EGP','818','Egyptian Pound');
INSERT INTO currencies(id, code, name) VALUES ('ERN','232','Nakfa');
INSERT INTO currencies(id, code, name) VALUES ('ETB','230','Ethiopian Birr');
INSERT INTO currencies(id, code, name) VALUES ('EUR','978','Euro');
INSERT INTO currencies(id, code, name) VALUES ('FJD','242','Fiji Dollar');
INSERT INTO currencies(id, code, name) VALUES ('FKP','238','Falkland Islands Pound');
INSERT INTO currencies(id, code, name) VALUES ('GBP','826','Pound Sterling');
INSERT INTO currencies(id, code, name) VALUES ('GEL','981','Lari');
INSERT INTO currencies(id, code, name) VALUES ('GHS','936','Ghana Cedi');
INSERT INTO currencies(id, code, name) VALUES ('GIP','292','Gibraltar Pound');
INSERT INTO currencies(id, code, name) VALUES ('GMD','270','Dalasi');
INSERT INTO currencies(id, code, name) VALUES ('GNF','324','Guinea Franc');
INSERT INTO currencies(id, code, name) VALUES ('GTQ','320','Quetzal');
INSERT INTO currencies(id, code, name) VALUES ('GYD','328','Guyana Dollar');
INSERT INTO currencies(id, code, name) VALUES ('HKD','344','Hong Kong Dollar');
INSERT INTO currencies(id, code, name) VALUES ('HNL','340','Lempira');
INSERT INTO currencies(id, code, name) VALUES ('HTG','332','Gourde');
INSERT INTO currencies(id, code, name) VALUES ('HUF','348','Forint');
INSERT INTO currencies(id, code, name) VALUES ('IDR','360','Rupiah');
INSERT INTO currencies(id, code, name) VALUES ('ILS','376','New Israeli Sheqel');
INSERT INTO currencies(id, code, name) VALUES ('INR','356','Indian Rupee');
INSERT INTO currencies(id, code, name) VALUES ('IQD','368','Iraqi Dinar');
INSERT INTO currencies(id, code, name) VALUES ('IRR','364','Iranian Rial');
INSERT INTO currencies(id, code, name) VALUES ('ISK','352','Iceland Krona');
INSERT INTO currencies(id, code, name) VALUES ('JMD','388','Jamaican Dollar');
INSERT INTO currencies(id, code, name) VALUES ('JOD','400','Jordanian Dinar');
INSERT INTO currencies(id, code, name) VALUES ('JPY','392','Yen');
INSERT INTO currencies(id, code, name) VALUES ('KES','404','Kenyan Shilling');
INSERT INTO currencies(id, code, name) VALUES ('KGS','417','Som');
INSERT INTO currencies(id, code, name) VALUES ('KHR','116','Riel');
INSERT INTO currencies(id, code, name) VALUES ('KMF','174','Comoro Franc');
INSERT INTO currencies(id, code, name) VALUES ('KPW','408','North Korean Won');
INSERT INTO currencies(id, code, name) VALUES ('KRW','410','Won');
INSERT INTO currencies(id, code, name) VALUES ('KWD','414','Kuwaiti Dinar');
INSERT INTO currencies(id, code, name) VALUES ('KYD','136','Cayman Islands Dollar');
INSERT INTO currencies(id, code, name) VALUES ('KZT','398','Tenge');
INSERT INTO currencies(id, code, name) VALUES ('LAK','418','Kip');
INSERT INTO currencies(id, code, name) VALUES ('LBP','422','Lebanese Pound');
INSERT INTO currencies(id, code, name) VALUES ('LKR','144','Sri Lanka Rupee');
INSERT INTO currencies(id, code, name) VALUES ('LRD','430','Liberian Dollar');
INSERT INTO currencies(id, code, name) VALUES ('LSL','426','Loti');
INSERT INTO currencies(id, code, name) VALUES ('LYD','434','Libyan Dinar');
INSERT INTO currencies(id, code, name) VALUES ('MAD','504','Moroccan Dirham');
INSERT INTO currencies(id, code, name) VALUES ('MDL','498','Moldovan Leu');
INSERT INTO currencies(id, code, name) VALUES ('MGA','969','Malagasy Ariary');
INSERT INTO currencies(id, code, name) VALUES ('MKD','807','Denar');
INSERT INTO currencies(id, code, name) VALUES ('MMK','104','Kyat');
INSERT INTO currencies(id, code, name) VALUES ('MNT','496','Tugrik');
INSERT INTO currencies(id, code, name) VALUES ('MOP','446','Pataca');
INSERT INTO currencies(id, code, name) VALUES ('MRU','929','Ouguiya');
INSERT INTO currencies(id, code, name) VALUES ('MUR','480','Mauritius Rupee');
INSERT INTO currencies(id, code, name) VALUES ('MVR','462','Rufiyaa');
INSERT INTO currencies(id, code, name) VALUES ('MWK','454','Kwacha');
INSERT INTO currencies(id, code, name) VALUES ('MXN','484','Mexican Peso');
INSERT INTO currencies(id, code, name) VALUES ('MXV','979','Mexican Unidad de Inversion (UDI)');
INSERT INTO currencies(id, code, name) VALUES ('MYR','458','Malaysian Ringgit');
INSERT INTO currencies(id, code, name) VALUES ('MZN','943','Mozambique Metical');
INSERT INTO currencies(id, code, name) VALUES ('NAD','516','Namibia Dollar');
INSERT INTO currencies(id, code, name) VALUES ('NGN','566','Naira');
INSERT INTO currencies(id, code, name) VALUES ('NIO','558','Cordoba Oro');
INSERT INTO currencies(id, code, name) VALUES ('NOK','578','Norwegian Krone');
INSERT INTO currencies(id, code, name) VALUES ('NPR','524','Nepalese Rupee');
INSERT INTO currencies(id, code, name) VALUES ('NZD','554','New Zealand Dollar');
INSERT INTO currencies(id, code, name) VALUES ('OMR','512','Rial Omani');
INSERT INTO currencies(id, code, name) VALUES ('PAB','590','Balboa');
INSERT INTO currencies(id, code, name) VALUES ('PEN','604','Nuevo Sol');
INSERT INTO currencies(id, code, name) VALUES ('PGK','598','Kina');
INSERT INTO currencies(id, code, name) VALUES ('PHP','608','Philippine Peso');
INSERT INTO currencies(id, code, name) VALUES ('PKR','586','Pakistan Rupee');
INSERT INTO currencies(id, code, name) VALUES ('PLN','985','Zloty');
INSERT INTO currencies(id, code, name) VALUES ('PYG','600','Guarani');
INSERT INTO currencies(id, code, name) VALUES ('QAR','634','Qatari Rial');
INSERT INTO currencies(id, code, name) VALUES ('RON','946','Romanian Leu');
INSERT INTO currencies(id, code, name) VALUES ('RSD','941','Serbian Dinar');
INSERT INTO currencies(id, code, name) VALUES ('RUB','643','Russian Ruble');
INSERT INTO currencies(id, code, name) VALUES ('RWF','646','Rwanda Franc');
INSERT INTO currencies(id, code, name) VALUES ('SAR','682','Saudi Riyal');
INSERT INTO currencies(id, code, name) VALUES ('SBD','090','Solomon Islands Dollar');
INSERT INTO currencies(id, code, name) VALUES ('SCR','690','Seychelles Rupee');
INSERT INTO currencies(id, code, name) VALUES ('SDG','938','Sudanese Pound');
INSERT INTO currencies(id, code, name) VALUES ('SEK','752','Swedish Krona');
INSERT INTO currencies(id, code, name) VALUES ('SGD','702','Singapore Dollar');
INSERT INTO currencies(id, code, name) VALUES ('SHP','654','Saint Helena Pound');
INSERT INTO currencies(id, code, name) VALUES ('SLE','925','Leone');
INSERT INTO currencies(id, code, name) VALUES ('SOS','706','Somali Shilling');
INSERT INTO currencies(id, code, name) VALUES ('SRD','968','Surinam Dollar');
INSERT INTO currencies(id, code, name) VALUES ('SSP','728','South Sudanese Pound');
INSERT INTO currencies(id, code, name) VALUES ('STN','930','Dobra');
INSERT INTO currencies(id, code, name) VALUES ('SVC','222','El Salvador Colon');
INSERT INTO currencies(id, code, name) VALUES ('SYP','760','Syrian Pound');
INSERT INTO currencies(id, code, name) VALUES ('SZL','748','Lilangeni');
INSERT INTO currencies(id, code, name) VALUES ('THB','764','Baht');
INSERT INTO currencies(id, code, name) VALUES ('TJS','972','Somoni');
INSERT INTO currencies(id, code, name) VALUES ('TMT','934','Turkmenistan New Manat');
INSERT INTO currencies(id, code, name) VALUES ('TND','788','Tunisian Dinar');
INSERT INTO currencies(id, code, name) VALUES ('TOP','776','Pa’anga');
INSERT INTO currencies(id, code, name) VALUES ('TRY','949','Turkish Lira');
INSERT INTO currencies(id, code, name) VALUES ('TTD','780','Trinidad and Tobago Dollar');
INSERT INTO currencies(id, code, name) VALUES ('TWD','901','New Taiwan Dollar');
INSERT INTO currencies(id, code, name) VALUES ('TZS','834','Tanzanian Shilling');
INSERT INTO currencies(id, code, name) VALUES ('UAH','980','Hryvnia');
INSERT INTO currencies(id, code, name) VALUES ('UGX','800','Uganda Shilling');
INSERT INTO currencies(id, code, name) VALUES ('USD','840','US Dollar');
INSERT INTO currencies(id, code, name) VALUES ('USN','997','US Dollar (Next day)');
INSERT INTO currencies(id, code, name) VALUES ('UYI','940','Uruguay Peso en Unidades Indexadas (URUIURUI)');
INSERT INTO currencies(id, code, name) VALUES ('UYU','858','Peso Uruguayo');
INSERT INTO currencies(id, code, name) VALUES ('UZS','860','Uzbekistan Sum');
INSERT INTO currencies(id, code, name) VALUES ('VED','926','Bolivar');
INSERT INTO currencies(id, code, name) VALUES ('VEF','937','Bolivar');
INSERT INTO currencies(id, code, name) VALUES ('VND','704','Dong');
INSERT INTO currencies(id, code, name) VALUES ('VUV','548','Vatu');
INSERT INTO currencies(id, code, name) VALUES ('WST','882','Tala');
INSERT INTO currencies(id, code, name) VALUES ('XAF','950','CFA Franc BEAC');
INSERT INTO currencies(id, code, name) VALUES ('XCD','951','East Caribbean Dollar');
INSERT INTO currencies(id, code, name) VALUES ('XDR','960','SDR (Special Drawing Right)');
INSERT INTO currencies(id, code, name) VALUES ('XOF','952','CFA Franc BCEAO');
INSERT INTO currencies(id, code, name) VALUES ('XPF','953','CFP Franc');
INSERT INTO currencies(id, code, name) VALUES ('XSU','994','Sucre');
INSERT INTO currencies(id, code, name) VALUES ('XUA','965','ADB Unit of Account');
INSERT INTO currencies(id, code, name) VALUES ('YER','886','Yemeni Rial');
INSERT INTO currencies(id, code, name) VALUES ('ZAR','710','Rand');
INSERT INTO currencies(id, code, name) VALUES ('ZMW','967','Zambian Kwacha');
INSERT INTO currencies(id, code, name) VALUES ('ZWL','932','Zimbabwe Dollar');

INSERT INTO languages (id, name) VALUES ('EN','English');
INSERT INTO languages (id, name) VALUES ('RU','Russian');